# Generated by Django 4.2.7 on 2023-11-17 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_book_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 17, 2, 35, 51, 319770, tzinfo=datetime.timezone.utc), help_text='format: YYYY-MM-DD'),
        ),
    ]
