# Generated by Django 4.2.7 on 2023-11-17 03:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_book_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.book_image_file_path),
        ),
    ]
